### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by lorenzo-dev1** [autonity/autonity#1063]
List of tasks, open issues and PRs that we need to address for the next release.

Issues are divided by priority, but order inside the same priority section has no particular meaning.

FYI, this is just my opinion and is not a result of team agreement. Please comment if you disagree / have something to add.

## Top priority (Blocking)

Issues to solve:
- [x] https://github.com/autonity/autonity/issues/882
- [x] https://github.com/autonity/autonity/issues/811
- [ ] https://github.com/autonity/autonity/issues/877 (to be discussed)

- [ ] https://github.com/autonity/autonity/issues/949 (I think we want this, but it requires reworking the autonity contract cache as it is not reliable right now. It might not be feasible in the time we have.)
- [ ] https://github.com/autonity/autonity/issues/1050

PR to merge:
- [x] https://github.com/autonity/autonity/pull/1053
- [x] https://github.com/autonity/autonity/pull/1059
- [x] https://github.com/autonity/autonity/pull/1061

Additional tasks:
- [ ] Update config for mainnet
  - [ ] decide if to use the conservative or default config for omission accountability
  - [ ] decide where to send withheld rewards
  - [ ] related: https://github.com/autonity/autonity/issues/1057
- [ ] Evaluate release performance with the perf-tool, and ensure the result is satisfying. If not, identify bottlenecks and improve them.

## Medium priority (we should try to merge it in, but not blocking)

Issues to solve:
- [x] https://github.com/autonity/autonity/issues/1034
- [ ] https://github.com/autonity/autonity/issues/985 (to be discussed)
- [ ] https://github.com/autonity/autonity/issues/1013 (verify if the issue is still valid)
- [x] https://github.com/autonity/autonity/issues/1062

PR to merge:
- [x] https://github.com/autonity/autonity/pull/1060

Additional tasks:
- [x] ensure that the p2p jailing cannot cause liveness problems (e.g. a part of the network p2p jails a validator that his the current proposer, while the other part of the network accepts his proposal)
- [x] ensure that the 10mb p2p packet limit cannot cause liveness issues when building a big block for some reason

## Nice to have

Issues to solve:
- [ ] https://github.com/autonity/autonity/issues/813
- [ ] https://github.com/autonity/autonity/issues/902
- [ ] https://github.com/autonity/autonity/issues/939
- [ ] https://github.com/autonity/autonity/issues/941
- [ ] https://github.com/autonity/autonity/issues/944
- [ ] https://github.com/autonity/autonity/issues/977
- [ ] https://github.com/autonity/autonity/issues/1014
- [ ] https://github.com/autonity/autonity/issues/1052 (to be discussed)
- [ ] https://github.com/autonity/autonity/issues/880

PR to merge:
- [x] https://github.com/autonity/autonity/pull/1038
- [x] https://github.com/autonity/autonity/pull/1041
- [x] https://github.com/autonity/autonity/pull/1019 (this PR is still WIP, but the currently pushed fix can still be included into the release)
- [ ] https://github.com/autonity/autonity/pull/1030

Additional tasks:
- [ ] add metrics for voting power connected + voting power in the core msg store.
- [x] do not block Core when posting events back to the aggregator (e.g. `RoundChangeEvent`). Currently this is done synchronously so there is the possibility that Core blocks if Aggregator is not reading. However it should not happen normally.
- [x] Ensure that LNTN:NTN conversion ratio (and similar operations) cannot be exploited by artificially increasing the ratio so much that it causes an overflow
- [x] Verify that the header extra data space that we allow is sufficient, we now have a lot more information stored there wrt before
- [x] Enforce maximum NTN supply in code (to be discussed)
- [x] Remove the concept of pending block from the code, since we now return the current block instead. Alternatively, this behaviour change can be documented in the docs.

**Comment by lorenzo-dev1** [comment]
Closing as we have issued the alpha release. Remaining high priority open points are captured in https://github.com/autonity/autonity/issues/1092.
