### ISSUE TITLE
Epoch Block header

### ISSUE THREAD

**Issue by yazzaoui** [autonity/autonity#885]
- [x] ADR draft for the epoch block header
- [x] Proof of concept implementation
- [ ] ADR proposal review
- [ ] Implementation

**Comment by lorenzo-dev1** [comment]
Closing as done
